### ISSUE TITLE
pr-metadata does not recognize new github review approvals

### ISSUE THREAD

**Issue by jasnell** [rvagg/iojs-tools#7]
The pr-metadata tool is not recognizing the new github review approvals. Run `pr-metadata https://github.com/nodejs/node/pull/8523` for example. It will return only one hit for LGTM (the one posted as a regular comment)

@Trott @rvagg

**Comment by jasnell** [comment]
It looks like the github API does not even surface the review comments that well:

https://api.github.com/repos/nodejs/node/pulls/8668/comments

**Comment by rvagg** [comment]
Working @ https://github.com/rvagg/iojs-tools/pull/8 but depends on some upstream PRs landing, found out how I can opt-in to an experimental API
